"""Adiciona a coluna is_weighted a tabela Product

Revision ID: 9c3f48107bd1
Revises: 15918d3a33c7
Create Date: 2025-12-03 07:46:46.565875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3f48107bd1'
down_revision: Union[str, None] = '15918d3a33c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_weighted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_weighted')
    # ### end Alembic commands ###